#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README_START = "<!-- PHASE6-RULES:START -->"
README_END = "<!-- PHASE6-RULES:END -->"
METHOD_START = "<!-- METHOD-VERSION:START -->"
METHOD_END = "<!-- METHOD-VERSION:END -->"


def write_if_changed(path: Path, content: str, check: bool, changed: list[Path]) -> None:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return
    changed.append(path)
    if not check:
        path.write_text(content, encoding="utf-8")


def ensure_asset(path: Path, prefix: str, check: bool, changed: list[Path]) -> None:
    text = path.read_text(encoding="utf-8")
    css = f'{prefix}assets/phase6.css?v=20260819-phase6'
    js = f'{prefix}assets/phase6.js?v=20260819-phase6'
    updated = text
    if "assets/phase6.css" not in updated:
        head_close = updated.find("</head>")
        if head_close == -1:
            raise RuntimeError(f"Missing </head> in {path}")
        updated = updated[:head_close] + f'  <link rel="stylesheet" href="{css}">\n' + updated[head_close:]
    if "assets/phase6.js" not in updated:
        body_close = updated.rfind("</body>")
        if body_close == -1:
            raise RuntimeError(f"Missing </body> in {path}")
        updated = updated[:body_close] + f'  <script src="{js}"></script>\n' + updated[body_close:]
    write_if_changed(path, updated, check, changed)


def method_version_block() -> str:
    return f'''{METHOD_START}
    <section class="method-section" id="method-version">
      <div class="method-section-heading">
        <div>
          <p class="eyebrow">METHODOLOGY VERSION</p>
          <h2>A controlled method, not static copy.</h2>
        </div>
        <div class="prose"><p>The public methodology is versioned so future changes in evidence handling, modelling transparency or interpretation can be distinguished from the method under which earlier episodes were published.</p></div>
      </div>
      <div class="method-version">
        <div class="method-version-head"><strong>Methodology version 1.0</strong><span>Updated August 2026</span></div>
        <div class="method-changelog"><strong>v1.0 · Aug 2026</strong><p>Initial public methodology formalized: seven-stage pipeline, Evidence Ladder, Evidence Profile interpretation, Assumption Ledger, emission-factor hierarchy, illustrative system boundary and canonical audit trail.</p></div>
      </div>
    </section>
{METHOD_END}'''


def update_method(check: bool, changed: list[Path]) -> None:
    path = ROOT / "method.html"
    text = path.read_text(encoding="utf-8")
    block = method_version_block()
    pattern = rf"{re.escape(METHOD_START)}.*?{re.escape(METHOD_END)}"
    if re.search(pattern, text, flags=re.S):
        updated = re.sub(pattern, block, text, flags=re.S)
    else:
        marker = '<section class="method-closing">'
        pos = text.find(marker)
        if pos == -1:
            raise RuntimeError("Cannot place methodology version block")
        updated = text[:pos] + block + "\n\n    " + text[pos:]
    write_if_changed(path, updated, check, changed)
    ensure_asset(path, "", check, changed)


def update_readme(check: bool, changed: list[Path]) -> None:
    path = ROOT / "README.md"
    text = path.read_text(encoding="utf-8")
    section = f'''{README_START}

## 29. Phase 6 — Model Passport, richer Impact Map and methodology versioning — mandatory

Phase 6 adds a compact transparency layer without introducing new episode facts that are not already registered.

### 29.1 Model Passport

Every published episode receives a registry-derived `MODEL PASSPORT` generated by `assets/phase6.js`.

The passport may display only fields already present in `episodes.json`:

- functional unit / reporting basis;
- headline result;
- principal LCA lens;
- main hotspot;
- Evidence confidence;
- Proxy dependence;
- Assumption sensitivity;
- Evidence basis;
- Main modelling uncertainty.

The passport must explicitly state that it introduces no additional assumptions. It must not fabricate system boundaries, factor lists, allocation rules or detailed assumptions that are not structured in the registry. Readers are directed to the episode inventory and registered source/model notes for the full public interpretation.

The user-facing export is the visual Epic Passport through `Print / Save as PDF`. Raw-text export is retired, and the original episode PDF is not exposed as a website download.

### 29.2 Atlas impact-scale context

Within The Impossible Atlas, `explore.html` retains logarithmic positioning and the non-comparability warning. Phase 6 adds expandable technical context for each plotted case using only registry fields:

- functional unit;
- main hotspot;
- Evidence confidence;
- Proxy dependence;
- Assumption sensitivity;
- direct link to the episode.

The added context must never convert the scale into a better/worse ranking.

### 29.3 Methodology versioning

`method.html` contains a visible methodology-version block. Current public version:

`Methodology version 1.0 · Updated August 2026`

Version changes must be substantive and documented in a short changelog. Do not increment the methodology version for purely visual, typographic or copy-editing changes.

Versioning does not silently reclassify or recalculate previously published episodes. Where a later methodological change affects interpretation of older cases, that relationship must be disclosed explicitly.

### 29.4 Canonical files and automation

Phase 6 canonical files:

- `assets/phase6.css`;
- `assets/phase6.js`;
- `scripts/phase6_sync.py`;
- `scripts/phase6_qa.py`.

`SEO Sync` must run `scripts/phase6_sync.py` after Phase 5 synchronization. `Site QA` must run the same synchronization in the QA workspace and then execute `scripts/phase6_qa.py`.

### Phase 6 QA

- [ ] Every published episode loads Phase 6 CSS and JavaScript after synchronization.
- [ ] Model Passport fields are registry-derived only.
- [ ] Printed/saved Passport retains the canonical episode URL and the interpretation disclaimer.
- [ ] No passport invents an unregistered system boundary, factor list or assumption set.
- [ ] Impact Map retains the non-comparability warning and gains expandable technical context.
- [ ] Method page displays `Methodology version 1.0` and `Updated August 2026`.
- [ ] Method changelog contains at least one explicit version entry.
- [ ] Phase 6 remains usable on mobile and does not alter catalogue-cover rules.

{README_END}'''
    pattern = rf"{re.escape(README_START)}.*?{re.escape(README_END)}"
    if re.search(pattern, text, flags=re.S):
        updated = re.sub(pattern, section, text, flags=re.S)
    else:
        updated = text.rstrip() + "\n\n---\n\n" + section + "\n"
    write_if_changed(path, updated, check, changed)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed: list[Path] = []

    for path in sorted((ROOT / "episodes").glob("*.html")):
        ensure_asset(path, "../", args.check, changed)
    ensure_asset(ROOT / "explore.html", "", args.check, changed)
    update_method(args.check, changed)
    update_readme(args.check, changed)

    if changed:
        verb = "would change" if args.check else "updated"
        for path in changed:
            print(f"Phase 6 {verb}: {path.relative_to(ROOT)}")
        return 1 if args.check else 0
    print("Phase 6 model transparency is synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
