name: Update catalogue cover bible

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-catalogue-cover-bible.yml

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update README
        run: python .github/update_catalogue_cover_bible.py
      - name: Commit README update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm .github/update_catalogue_cover_bible.py
          rm .github/workflows/update-catalogue-cover-bible.yml
          git add -A
          git commit -m "Define canonical catalogue cover style for future episodes"
          git push
